try{
    console.log("try block starts here");
    console.log(x); // error -> reference 
    console.log("try block ends here");
     
    //a-line
    //b-line
    

}
catch(e) {
    //define krte h, error k sath app kya krna chahte h
    //retry logic
    //fallback mechanism
    //logging
    //customer

    console.log("I AM INSIDE CATCH BLOCK");
    console.log("Your error is here: ", e);
    
    

}
finally{
    console.log("I will run everytime");
}

// finally-block : will run everyTime



